# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

sudo: required

## would like to update to container infrastructure, but both r-travis
##  (below) and metacran/r-builder pkg-build files appear to require sudo ...
## http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh aptget_install texlive-latex-extra
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests
#script: LME4_TEST_LEVEL=2 ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
